### ISSUE TITLE
Improve GIF embed code

### ISSUE THREAD

**Issue by 7studio** [TweetPressFr/wp-giphy-oembed#1]
Hi Julien,

As I was interested by the support of Giphy into the oEmbed part of WordPress, I would like to ask you and share some details.

Why do you choose to handle Giphy GIFs as a "rich" type?
By default, Giphy chooses to handle their GIFs as "photo" instead of "rich" content through their oEmbed API (e.g.: http://giphy.com/services/oembed?url=https%3A%2F%2Fgiphy.com%2Fgifs%2Fcant-hardly-wait-kW8mnYSNkUYKc). 
I totally agree with your choice but do you have some reasons about it?
I sent an email to the Giphy team to talk about a new way to pick up their GIF embed code through their oEmbed API but they don't care about it: "Thanks for the suggestion! This isn't something we currently offer." :disappointed:

We both use the same way about the GIF embed code by choosing the `<iframe>` version. 
But according to the Giphy's post "[How To Embed Giphy GIFs On Your Website](https://giphy.com/posts/how-to-embed-giphy-gifs-on-your-website)", it seems that it is better to use their HTML5 embed version. There is not a big difference with your code, just one more parameter into
the URI: `html5=true`. IMHO, it is worthwhile to add it to your code.
First of all, I would like to use the `<script>` version, but after some tests, it seems that Giphy has done bad choices for this version: https://twitter.com/7studio/status/854616793163476992
In any case, the `<iframe>` version is better to deal with CSPs :blush:

Just to finish, it will be interesting that your plugin supports the three types 
of URL like the [Giphy oEmbed API endpoint](https://github.com/iamcal/oembed/issues/224):
- `https://giphy.com/gifs/*`
- `http://gph.is/*`
- `https://media.giphy.com/media/*/giphy.gif`

To achieve this, I used another way in my code: https://github.com/7studio/thistle/commit/f6740db437b395c429499ab08289e49354553d2c

Hope this issue contributes to your plugin,
Xavier.

**Comment by TweetPressFr** [comment]
Hi Xavier,

Huge Thanks for your detailed and very interesting issue. I'll check this HTML5 support and it will be added if it's better for users (which seems to be the case).

I must admit I've created this plugin mostly "because I can" which is to me a good reason but not really informative. See https://dev73.tweetpress.fr/plugin/giphy-oembed-wordpress.html (French)

As you know "11 months ago" is like centuries in our world ^^ so I would not say this is the best approach BUT I prefer this way cause this is [to me] the WP way : like YouTube and Twitter for example, Giphy is a typical case of "content provider" which means oEmbed provider in most case in WordPress. In addition to this they provide supports for iframe.

In fact I don't handle width and height in my code which is not really a good thing so I guess it could be improved by far (especially with alliases you're right). Thanks for your hints and examples. I'll probably use them.

**Comment by TweetPressFr** [comment]
Sorry got no time for this, here are the points :

- The three types are already taken into account, I've checked this again. My regex covers all the thing
- I've added support for html5  :)
- I don't understand their inline styles for responsive, to me this must be handled by css and other stuffs I don't want to introduce it => 
`<div style="width:100%;height:0;padding-bottom:61%;position:relative;">`
